### no content-type, empty body, expect 400
POST http://localhost:3000/top-up

### bad currency
POST http://localhost:3000/top-up
content-type: application/json

{
  "idempotencyKey": "id1",
  "userId": "lara",
  "currency": "xxx",
  "value": "1.00"
}

### valid request with merchant data, JSON
POST http://localhost:3000/top-up
content-type: application/json

{
  "idempotencyKey": "id2",
  "userId": "mehmet",
  "currency": "TRY",
  "value": "40.00",
  "merchantData": "{\"valid\":true}"
}

### valid request with merchant data, JSON (another currency)
POST http://localhost:3000/top-up
content-type: application/json

{
  "idempotencyKey": "id3",
  "userId": "mehmet",
  "currency": "USD",
  "value": "5.00",
  "merchantData": "{\"valid\":true}"
}

### valid request with merchant data, protobuf
POST http://localhost:3000/top-up
content-type: application/protobuf

< ./topup-1.bin
